# Generated by Django 3.0.4 on 2020-04-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.URLField(verbose_name='Url imagen')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('link', models.URLField(verbose_name='URL Sitio Web')),
                ('fch_creado', models.DateField(auto_now_add=True)),
                ('fch_mod', models.DateField(auto_now=True)),
            ],
        ),
    ]
